export * from './signin/signin.component';
export * from './home-page/home-page.component';
export * from './categories/categories.component';
export * from './accueil/accueil.component';
export * from './detail/detail.component';
export * from './forgot-pass/forgot-pass.component';
export * from './otp/otp.component';
export * from './its-done/its-done.component';
export * from './signup/signup.component';